export const application = {
    SHOW: 'APPLICATION_SHOW',
    SET_LOADING: 'APPLICATION_SET_LOADING',
    REQUEST_PAGE_CONTENT: 'APPLICATION_REQUEST_PAGE_CONTENT',
    SET_PAGE: 'APPLICATION_SET_PAGE',
};

export const authentication = {
    SHOW_SCREEN: 'AUTHENTICATION_SHOW_SCREEN',
    RISE_LOGO: 'AUTHENTICATION_RISE_LOGO',
    SHOW_FORM: 'AUTHENTICATION_SHOW_FORM',
    SHOW_PASSWORD : 'AUTHENTICATION_SHOW_PASSWORD',
    CHANGE_EMAIL : 'AUTHENTICATION_CHANGE_EMAIL',
    SET_EMAIL : 'AUTHENTICATION_SET_EMAIL',
    CHANGE_PASSWORD : 'AUTHENTICATION_CHANGE_PASSWORD',
    SET_PASSWORD : 'AUTHENTICATION_SET_PASSWORD',
    SET_USER: 'AUTHENTICATION_SET_USER',
    VALID_EMAIL: 'AUTHENTICATION_VALID_EMAIL',
    VALID_PASSWORD: 'AUTHENTICATION_VALID_PASSWORD',
    VALIDATING: 'AUTHENTICATION_VALIDATING',
    REQUEST_AUTHENTICATION: 'AUTHENTICATION_REQUEST_AUTHENTICATION',
    LOGOUT: 'AUTHENTICATION_LOGOUT',
    WEB_STORAGE_AUTH: 'AUTHENTICATION_WEB_STORAGE_AUTH',
    REFRESHING: 'AUTHENTICATION_REFRESHING',
};

export const mainMessage = {
    OPEN: 'MAIN_MESSAGE_OPEN',
    SEVERITY: 'MAIN_MESSAGE_SEVERITY',
    MESSAGE: 'MAIN_MESSAGE_MESSAGE',
};

export const menu = {
    OPEN: 'MENU_OPEN',
};

export const categories = {
    SET_ITEMS: 'CATEGORIES_SET_ITEMS',
    ACTIONS_SCREEN: 'CATEGORIES_ACTIONS_SCREEN',
    SET_FORM: 'CATEGORIES_SET_FORM',
    CHANGE_FIELD_CONTENT: 'CATEGORIES_CHANGE_FIELD_CONTENT',
    SET_FIELD_CONTENT: 'CATEGORIES_SET_FIELD_CONTENT',
    ADD: 'CATEGORIES_ADD',
    EDIT: 'CATEGORIES_EDIT',
    RESET: 'CATEGORIES_RESET',
    SAVE: 'CATEGORIES_SAVE',
    SAVED: 'CATEGORIES_SAVED',
    SET_IMAGE_FILE: 'CATEGORIES_SET_IMAGE_FILE',
    SAVING: 'CATEGORIES_SAVING',
    ERROR_FIELD: 'CATEGORIES_ERROR_FIELD',
    REQUEST_DELETE: 'CATEGORIES_REQUEST_DELETE',
    DELETE: 'CATEGORIES_DELETE',
    REMOVING: 'CATEGORIES_REMOVING',
    REQUEST_CATEGORY: 'CATEGORIES_REQUEST_CATEGORY',
    SET_CATEGORY: 'CATEGORIES_SET_CATEGORY',
    SET_FORM_PRODUCTS: 'CATEGORIES_SET_FORM_PRODUCTS',
};

export const products = {
    SET_ITEMS: 'PRODUCTS_SET_ITEMS',
    ACTIONS_SCREEN: 'PRODUCTS_ACTIONS_SCREEN',
    SET_FORM: 'PRODUCTS_SET_FORM',
    CHANGE_FIELD_CONTENT: 'PRODUCTS_CHANGE_FIELD_CONTENT',
    SET_FIELD_CONTENT: 'PRODUCTS_SET_FIELD_CONTENT',
    ADD: 'PRODUCTS_ADD',
    EDIT: 'PRODUCTS_EDIT',
    ADD_IMAGE: 'PRODUCTS_ADD_IMAGE',
    REMOVE_IMAGE: 'PRODUCTS_REMOVE_IMAGE',
    SET_DEFAULT_IMAGE: 'PRODUCTS_SET_DEFAULT_IMAGE',
    SET_FORM_IMAGES: 'PRODUCTS_SET_FORM_IMAGES',
    SET_IMAGE_FILE: 'PRODUCTS_SET_IMAGE_FILE',
    SAVE: 'PRODUCTS_SAVE',
    SAVED: 'PRODUCTS_SAVED',
    SAVING: 'PRODUCTS_SAVING',
    SET_FORM_ERRORS: 'PRODUCTS_SET_FORM_ERRORS',
    RESET: 'PRODUCTS_RESET',
    CHECK_ERRORS: 'PRODUCTS_CHECK_ERRORS',
    FORM_IMAGE_ERRORS: 'PRODUCTS_FORM_IMAGE_ERRORS',
    REQUEST_DELETE: 'PRODUCTS_REQUEST_DELETE',
    DELETE: 'PRODUCTS_DELETE',
    REMOVING: 'PRODUCTS_REMOVING',
};

export const categoryProducts = {
    OPEN: 'CATEGORY_PRODUCTS_OPEN',
    HIDE: 'CATEGORY_PRODUCTS_HIDE',
    REQUEST_PRODUCTS: 'CATEGORY_PRODUCTS_REQUEST_PRODUCTS',
    SET_PRODUCTS: 'CATEGORY_PRODUCTS_SET_PRODUCTS',
    SELECT_DIALOG_PRODUCT: 'CATEGORY_PRODUCTS_SELECT_DIALOG_PRODUCT',
    SET_SELECTED: 'CATEGORY_PRODUCTS_SET_SELECTED',
    ASSIGN_PRODUCTS: 'CATEGORY_PRODUCTS_ASSIGN_PRODUCTS',
    SELECT_ASSIGNED_PRODUCT: 'CATEGORY_PRODUCTS_SELECT_ASSIGNED_PRODUCT',
    SET_REMOVE_ASSIGNED: 'CATEGORY_PRODUCTS_SET_REMOVE_ASSIGNED',
    REMOVE_ASSIGNED_PRODUCTS: 'CATEGORY_PRODUCTS_REMOVE_ASSIGNED_PRODUCTS',
};

export const product = {
    SET: 'PRODUCT_SET',
    SET_IMAGE: 'PRODUCT_SET_IMAGE',
};
